apiVersion: sensa.io/v1alpha1
kind: TopDomain
metadata:
  name: financeiro
  namespace: catalog
  labels:
    sensa.io/owner: platform-team
  annotations:
    sensa.io/description: "Domínio de negócio responsável por todas as operações financeiras da empresa"
spec:
  displayName: "Financeiro"
  businessUnit: "CFO"
  owner: platform-team
