apiVersion: sensa.io/v1alpha1
kind: TopDomain
metadata:
  name: operacoes
  namespace: catalog
  labels:
    sensa.io/owner: platform-team
  annotations:
    sensa.io/description: "Domínio de negócio responsável por operações logísticas e entrega"
spec:
  displayName: "Operações"
  businessUnit: "COO"
  owner: platform-team
