apiVersion: sensa.io/v1alpha1
kind: Domain
metadata:
  name: pagamentos
  namespace: catalog
  labels:
    sensa.io/owner: payments-squad
    sensa.io/top-domain: financeiro
  annotations:
    sensa.io/description: "Área responsável por processamento de pagamentos, recebimentos e conciliação"
spec:
  displayName: "Pagamentos"
  topDomain: financeiro
  owner: payments-squad
