apiVersion: sensa.io/v1alpha1
kind: SubDomain
metadata:
  name: processamento-pagamentos
  namespace: catalog
  labels:
    sensa.io/owner: payments-squad
    sensa.io/domain: pagamentos
    sensa.io/top-domain: financeiro
  annotations:
    sensa.io/description: "Subárea responsável pelo processamento em tempo real de transações de pagamento"
spec:
  displayName: "Processamento de Pagamentos"
  domain: pagamentos
  owner: payments-squad
